-- ============================================================================
--  YES ERP · Technician Time Management Module
--  Phase 0 schema — new TM_* objects (run as the application schema owner)
--  Oracle 19c+ . Existing ERP tables (AMM_USER_DETAILS, PPM_EMPLOYEE_DETAILS,
--  MMM_PARTY_DETAILS, MTL_TRANSACTION_JOB_OTHER_DTLS) are referenced, not created.
-- ============================================================================

-- ---------- Sequences -------------------------------------------------------
CREATE SEQUENCE TM_USER_ROLE_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_WORK_TYPE_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_INDUSTRY_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_CUST_IND_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_LABOUR_RATE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_DUTY_TIMING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_CALENDAR_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_TASK_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_TASK_STD_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_TIME_SHEET_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TM_TIME_LINE_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;

-- ---------- Security: application role assignment ---------------------------
CREATE TABLE TM_USER_ROLE
(
  TUR_ID               NUMBER(10)      NOT NULL,
  TUR_USER_ID          NUMBER(10)      NOT NULL,   -- FK -> AMM_USER_DETAILS.USER_ID
  TUR_ROLE_CODE        VARCHAR2(15)    NOT NULL,   -- USER | ADMIN | SITEADMIN
  TUR_ACTIVE_YN        VARCHAR2(1)     DEFAULT 'Y',
  TUR_CREATION_USER_ID NUMBER(10),
  TUR_CREATION_DATE    DATE            DEFAULT SYSDATE,
  TUR_UPDATE_USER_ID   NUMBER(10),
  TUR_UPDATE_DATE      DATE,
  CONSTRAINT TM_USER_ROLE_PK PRIMARY KEY (TUR_ID),
  CONSTRAINT TM_USER_ROLE_CHK CHECK (TUR_ROLE_CODE IN ('USER','ADMIN','SITEADMIN'))
);
CREATE INDEX TM_USER_ROLE_IX1 ON TM_USER_ROLE (TUR_USER_ID, TUR_ACTIVE_YN);

-- ---------- Master: Work / Labour Type -------------------------------------
CREATE TABLE TM_WORK_TYPE
(
  WORK_TYPE_CODE       VARCHAR2(15)    NOT NULL,
  WORK_TYPE_NAME       VARCHAR2(100)   NOT NULL,
  CATEGORY             VARCHAR2(20),               -- CHARGEABLE | NONCHARGEABLE | WARRANTY
  COST_TREATMENT       VARCHAR2(20),               -- REVENUE | EXPENSE
  SUB_TYPE             VARCHAR2(30),               -- Training | Redo | Housekeeping | Idle | Travel
  ACTIVE_YN            VARCHAR2(1)     DEFAULT 'Y',
  CREATION_USER_ID     NUMBER(10),
  CREATION_DATE        DATE            DEFAULT SYSDATE,
  UPDATE_USER_ID       NUMBER(10),
  UPDATE_DATE          DATE,
  CONSTRAINT TM_WORK_TYPE_PK PRIMARY KEY (WORK_TYPE_CODE)
);

-- ---------- Master: Industry -----------------------------------------------
CREATE TABLE TM_INDUSTRY
(
  INDUSTRY_CODE        VARCHAR2(15)    NOT NULL,
  INDUSTRY_NAME        VARCHAR2(100)   NOT NULL,
  ACTIVE_YN            VARCHAR2(1)     DEFAULT 'Y',
  CREATION_USER_ID     NUMBER(10),
  CREATION_DATE        DATE            DEFAULT SYSDATE,
  UPDATE_USER_ID       NUMBER(10),
  UPDATE_DATE          DATE,
  CONSTRAINT TM_INDUSTRY_PK PRIMARY KEY (INDUSTRY_CODE)
);

-- ---------- Master: Customer -> Industry mapping ---------------------------
CREATE TABLE TM_CUST_INDUSTRY_MAP
(
  CIM_ID               NUMBER(10)      NOT NULL,
  CIM_CUSTOMER_CODE    VARCHAR2(25)    NOT NULL,   -- MMM_PARTY_DETAILS.MPD_PARTY_CODE
  CIM_INDUSTRY_CODE    VARCHAR2(15)    NOT NULL,
  CIM_DEFAULT_LOCATION VARCHAR2(20),
  CIM_EFFECTIVE_FROM   DATE,
  CIM_ACTIVE_YN        VARCHAR2(1)     DEFAULT 'Y',
  CIM_CREATION_USER_ID NUMBER(10),
  CIM_CREATION_DATE    DATE            DEFAULT SYSDATE,
  CONSTRAINT TM_CUST_IND_PK PRIMARY KEY (CIM_ID)
);
CREATE INDEX TM_CUST_IND_IX1 ON TM_CUST_INDUSTRY_MAP (CIM_CUSTOMER_CODE, CIM_ACTIVE_YN);

-- ---------- Master: Labour Rate (Location x Industry x Time Type) ----------
CREATE TABLE TM_LABOUR_RATE
(
  LR_ID                NUMBER(10)      NOT NULL,
  LR_LOCATION          VARCHAR2(20)    NOT NULL,   -- Field | Workshop | Service
  LR_INDUSTRY_CODE     VARCHAR2(15),
  LR_TIME_TYPE         VARCHAR2(10),               -- NORMAL | OVERTIME (optional)
  LR_RATE              NUMBER(12,2)    NOT NULL,    -- charge rate
  LR_COST_RATE         NUMBER(12,2),                -- COGS rate
  LR_OT_MULTIPLIER     NUMBER(5,2)     DEFAULT 1.5,
  LR_EFFECTIVE_FROM    DATE,
  LR_ACTIVE_YN         VARCHAR2(1)     DEFAULT 'Y',
  LR_CREATION_USER_ID  NUMBER(10),
  LR_CREATION_DATE     DATE            DEFAULT SYSDATE,
  CONSTRAINT TM_LABOUR_RATE_PK PRIMARY KEY (LR_ID)
);
CREATE INDEX TM_LABOUR_RATE_IX1 ON TM_LABOUR_RATE (LR_LOCATION, LR_INDUSTRY_CODE, LR_ACTIVE_YN);

-- ---------- Master: Duty Timing & benchmark --------------------------------
CREATE TABLE TM_DUTY_TIMING
(
  DT_ID                NUMBER(10)      NOT NULL,
  DT_NAME              VARCHAR2(50),
  DT_START             VARCHAR2(5)     DEFAULT '08:00',  -- HH:MM
  DT_END               VARCHAR2(5)     DEFAULT '17:00',  -- HH:MM
  DT_LUNCH_HOURS       NUMBER(4,2)     DEFAULT 0.5,
  DT_WEEKEND_DAYS      VARCHAR2(100)   DEFAULT 'Friday,Saturday',
  DT_MONTHLY_BENCHMARK NUMBER(6,1)     DEFAULT 192,
  ACTIVE_YN            VARCHAR2(1)     DEFAULT 'Y',
  CREATION_USER_ID     NUMBER(10),
  CREATION_DATE        DATE            DEFAULT SYSDATE,
  CONSTRAINT TM_DUTY_TIMING_PK PRIMARY KEY (DT_ID)
);

-- ---------- Master: Working calendar / holidays ----------------------------
CREATE TABLE TM_CALENDAR
(
  CAL_ID               NUMBER(10)      NOT NULL,
  CAL_DATE             DATE            NOT NULL,
  CAL_HOLIDAY_NAME     VARCHAR2(100),
  CAL_IS_HOLIDAY_YN    VARCHAR2(1)     DEFAULT 'Y',
  CREATION_USER_ID     NUMBER(10),
  CREATION_DATE        DATE            DEFAULT SYSDATE,
  CONSTRAINT TM_CALENDAR_PK PRIMARY KEY (CAL_ID)
);

-- ---------- Master: Task ----------------------------------------------------
CREATE TABLE TM_TASK
(
  TASK_CODE            VARCHAR2(15)    NOT NULL,
  TASK_NAME            VARCHAR2(100)   NOT NULL,
  TASK_GROUP           VARCHAR2(50),
  SEQ_NO               NUMBER(5),
  DEFAULT_SKILL        VARCHAR2(30),
  STD_HOURS            NUMBER(8,2)     DEFAULT 0,
  CHARGEABLE_YN        VARCHAR2(1)     DEFAULT 'Y',
  ACTIVE_YN            VARCHAR2(1)     DEFAULT 'Y',
  CREATION_USER_ID     NUMBER(10),
  CREATION_DATE        DATE            DEFAULT SYSDATE,
  UPDATE_USER_ID       NUMBER(10),
  UPDATE_DATE          DATE,
  CONSTRAINT TM_TASK_PK PRIMARY KEY (TASK_CODE)
);

-- ---------- Master: Task Standard Hours (by equipment dimensions) ----------
CREATE TABLE TM_TASK_STD
(
  TST_ID               NUMBER(10)      NOT NULL,
  TST_MANUFACTURER     VARCHAR2(50),
  TST_MODEL            VARCHAR2(50),
  TST_SERIES           VARCHAR2(50),
  TST_COMPONENT        VARCHAR2(50),
  TST_TASK_CODE        VARCHAR2(15)    NOT NULL,
  TST_STD_HOURS        NUMBER(8,2)     NOT NULL,
  TST_ACCEPT_BENCHMARK VARCHAR2(200),
  ACTIVE_YN            VARCHAR2(1)     DEFAULT 'Y',
  CREATION_USER_ID     NUMBER(10),
  CREATION_DATE        DATE            DEFAULT SYSDATE,
  CONSTRAINT TM_TASK_STD_PK PRIMARY KEY (TST_ID)
);
CREATE INDEX TM_TASK_STD_IX1 ON TM_TASK_STD (TST_TASK_CODE, TST_MANUFACTURER, TST_MODEL);

-- ---------- Transaction: Time Sheet header ---------------------------------
CREATE TABLE TM_TIME_SHEET
(
  TS_ID                NUMBER(10)      NOT NULL,
  TS_SHEET_NO          VARCHAR2(25)    NOT NULL,
  TS_POSTING_DATE      DATE            NOT NULL,
  TS_JOB_CODE          VARCHAR2(25)    NOT NULL,   -- MTL_TRANSACTION_JOB_OTHER_DTLS.MTJ_JOB_CODE
  TS_CUSTOMER_CODE     VARCHAR2(25),
  TS_CUSTOMER_NAME     VARCHAR2(200),
  TS_EQUIPMENT         VARCHAR2(200),
  TS_INDUSTRY_CODE     VARCHAR2(15),
  TS_LOCATION          VARCHAR2(20),
  TS_WORK_TYPE_CODE    VARCHAR2(15),
  TS_JOB_STATUS        VARCHAR2(15),
  TS_TOTAL_NET_HOURS   NUMBER(10,2)    DEFAULT 0,
  TS_TOTAL_LABOUR_COST NUMBER(14,2)    DEFAULT 0,
  TS_NORMAL_HOURS      NUMBER(10,2)    DEFAULT 0,
  TS_OT_HOURS          NUMBER(10,2)    DEFAULT 0,
  TS_STD_HOURS         NUMBER(10,2)    DEFAULT 0,
  TS_REMARKS           VARCHAR2(1000),
  TS_ACTIVE_YN         VARCHAR2(1)     DEFAULT 'Y',
  TS_CREATION_USER_ID  NUMBER(10),
  TS_CREATION_DATE     DATE            DEFAULT SYSDATE,
  TS_UPDATE_USER_ID    NUMBER(10),
  TS_UPDATE_DATE       DATE,
  CONSTRAINT TM_TIME_SHEET_PK PRIMARY KEY (TS_ID),
  CONSTRAINT TM_TIME_SHEET_UK UNIQUE (TS_SHEET_NO)
);
CREATE INDEX TM_TIME_SHEET_IX1 ON TM_TIME_SHEET (TS_POSTING_DATE, TS_CREATION_USER_ID);
CREATE INDEX TM_TIME_SHEET_IX2 ON TM_TIME_SHEET (TS_JOB_CODE);

-- ---------- Transaction: Time Line (per Task, key = Job No + Task) ----------
CREATE TABLE TM_TIME_LINE
(
  TL_ID                NUMBER(10)      NOT NULL,
  TL_TS_ID             NUMBER(10)      NOT NULL,
  TL_LINE_NO           NUMBER(5),
  TL_TASK_CODE         VARCHAR2(15),
  TL_TASK_NAME         VARCHAR2(100),
  TL_STD_HOURS         NUMBER(8,2)     DEFAULT 0,
  TL_TECH_CODE         VARCHAR2(15),               -- PPM_EMPLOYEE_DETAILS.PEMP_EMP_CODE
  TL_TECH_NAME         VARCHAR2(200),
  TL_SKILL             VARCHAR2(30),
  TL_START_DT          DATE            NOT NULL,
  TL_END_DT            DATE            NOT NULL,
  TL_LUNCH_HOURS       NUMBER(6,2)     DEFAULT 0,
  TL_NET_HOURS         NUMBER(10,2)    DEFAULT 0,
  TL_TIME_TYPE         VARCHAR2(10),               -- NORMAL | OVERTIME
  TL_RATE              NUMBER(12,2)    DEFAULT 0,
  TL_LABOUR_COST       NUMBER(14,2)    DEFAULT 0,
  TL_JOB_CODE          VARCHAR2(25),
  TL_CREATION_USER_ID  NUMBER(10),
  TL_CREATION_DATE     DATE            DEFAULT SYSDATE,
  CONSTRAINT TM_TIME_LINE_PK PRIMARY KEY (TL_ID),
  CONSTRAINT TM_TIME_LINE_FK FOREIGN KEY (TL_TS_ID) REFERENCES TM_TIME_SHEET (TS_ID)
);
CREATE INDEX TM_TIME_LINE_IX1 ON TM_TIME_LINE (TL_TS_ID);
CREATE INDEX TM_TIME_LINE_IX2 ON TM_TIME_LINE (TL_JOB_CODE, TL_TASK_CODE);

COMMIT;
-- End of schema
