-- One-time cleanup of duplicate seed rows created by repeated seed runs.
DELETE FROM TM_LABOUR_RATE
 WHERE LR_ID NOT IN (
   SELECT MIN(LR_ID) FROM TM_LABOUR_RATE
    GROUP BY LR_LOCATION, NVL(LR_INDUSTRY_CODE,'*'), NVL(LR_TIME_TYPE,'*'));

DELETE FROM TM_DUTY_TIMING
 WHERE DT_ID NOT IN (
   SELECT MIN(DT_ID) FROM TM_DUTY_TIMING GROUP BY NVL(DT_NAME,'*'));

COMMIT;
